// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUsers(ctx context.Context) error
	GetAllChirps(ctx context.Context) ([]Chirp, error)
	GetChirpByID(ctx context.Context, id uuid.UUID) (Chirp, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
