// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUsers(ctx context.Context) error
	DeleteChirpByID(ctx context.Context, id uuid.UUID) error
	GetAllChirpsAsc(ctx context.Context, authorID uuid.NullUUID) ([]Chirp, error)
	GetAllChirpsDesc(ctx context.Context, authorID uuid.NullUUID) ([]Chirp, error)
	GetChirpByID(ctx context.Context, id uuid.UUID) (Chirp, error)
	GetRefreshTokenByID(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	RevokeRefreshToken(ctx context.Context, token string) error
	UpdateChirpyRedFlag(ctx context.Context, arg UpdateChirpyRedFlagParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
