### Polka Webhook (unauthorized)
# Returns 401 Unauthorized when the Authorization header is missing or invalid
POST http://localhost:8080/api/polka/webhooks HTTP/1.1
Content-Type: application/json

{"event": "user.upgraded", "data": {"user_id": "26e35c16-6a65-4319-8556-e3e6a15e6b05"}}

### Polka Webhook (authorized)
# Upgrades the user to Chirpy Red and returns 204 No Content
# The key f271c81ff7084ee5b99a5091b42d486e is a dummy key, its ok to commit :)
POST http://localhost:8080/api/polka/webhooks HTTP/1.1
Content-Type: application/json
Authorization: ApiKey f271c81ff7084ee5b99a5091b42d486e

{"event": "user.upgraded", "data": {"user_id": "26e35c16-6a65-4319-8556-e3e6a15e6b05"}}

### Polka Webhook (authorized, unhandled event)
# Returns 204 No Content for events other than user.upgraded
# The key f271c81ff7084ee5b99a5091b42d486e is a dummy key, its ok to commit :)
POST http://localhost:8080/api/polka/webhooks HTTP/1.1
Content-Type: application/json
Authorization: ApiKey f271c81ff7084ee5b99a5091b42d486e

{"event": "user.deleted", "data": {"user_id": "26e35c16-6a65-4319-8556-e3e6a15e6b05"}}
